- name: setup-java
  uses: olafurpg/setup-scala@v5
  with:
    # The Java version to install, a string matching the output format from  `jabba ls-remote`. For example, "adopt@1.8" for the latest AdoptOpenJDK 8 version, "adopt@1.11" for the latest AdoptOpenJDK 11 version, or "graalvm@" for the latest GraalVM version.

    java-version: # optional, default is adopt@1.8
    # The Jabba version to install.
    jabba-version: # optional, default is 0.11.2


public class Punkt {
    private double x;
    private double y;

    public Punkt(double x, double y) {
        this.x = x;
        this.y = y;
    }

    public Punkt() {
        this(0, 0);
    }

    public Punkt(Punkt punkt) {
        this(punkt.x, punkt.y);
    }

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public double distance(Punkt punkt){
        double dx = Math.abs(this.getX() - punkt.getX());
        double dy = Math.abs(this.getY() - punkt.getY());
        return Math.sqrt( dx * dx + dy * dy);
    }
}
